// <auto-generated />
using System;
using ChameleonFutureAcademyAdminApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ChameleonFutureAcademyAdminApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("activity_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("body");

                    b.Property<int>("ContentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("explanation");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("title");

                    b.HasKey("ActivityId");

                    b.HasIndex("ContentId")
                        .IsUnique();

                    b.ToTable("cfa_activity");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.ActivityOption", b =>
                {
                    b.Property<int>("ActivityOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("activity_option_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityOptionId"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("activity_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_correct");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("label");

                    b.HasKey("ActivityOptionId");

                    b.HasIndex("ActivityId", "Description")
                        .IsUnique();

                    b.HasIndex("ActivityId", "Label")
                        .IsUnique();

                    b.ToTable("cfa_activity_option");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("badge_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("course_id");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("title");

                    b.HasKey("BadgeId");

                    b.HasIndex("CourseId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("cfa_badge");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("content_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("course_id");

                    b.Property<int>("Position")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("type");

                    b.HasKey("ContentId");

                    b.HasIndex("CourseId", "Position")
                        .IsUnique();

                    b.ToTable("cfa_content");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("course_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("description");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("title");

                    b.HasKey("CourseId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("cfa_user_account");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.CourseTag", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("course_id");

                    b.Property<int>("TagId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("tag_id");

                    b.HasKey("CourseId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("cfa_course_tag");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("lesson_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("body");

                    b.Property<int>("ContentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("title");

                    b.HasKey("LessonId");

                    b.HasIndex("ContentId")
                        .IsUnique();

                    b.ToTable("cfa_lesson");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("tag_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("description");

                    b.HasKey("TagId");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("cfa_tag");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Activity", b =>
                {
                    b.HasOne("ChameleonFutureAcademyAdminApi.Models.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.ActivityOption", b =>
                {
                    b.HasOne("ChameleonFutureAcademyAdminApi.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Badge", b =>
                {
                    b.HasOne("ChameleonFutureAcademyAdminApi.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Content", b =>
                {
                    b.HasOne("ChameleonFutureAcademyAdminApi.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.CourseTag", b =>
                {
                    b.HasOne("ChameleonFutureAcademyAdminApi.Models.Course", "Course")
                        .WithMany("CourseTags")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChameleonFutureAcademyAdminApi.Models.Tag", "Tag")
                        .WithMany("CourseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Lesson", b =>
                {
                    b.HasOne("ChameleonFutureAcademyAdminApi.Models.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Course", b =>
                {
                    b.Navigation("CourseTags");
                });

            modelBuilder.Entity("ChameleonFutureAcademyAdminApi.Models.Tag", b =>
                {
                    b.Navigation("CourseTags");
                });
#pragma warning restore 612, 618
        }
    }
}
